#!/usr/bin/env python3

import json
import os
import sys

from lunr import lunr


def main():
    if len(sys.argv) != 2:
        print("Usage: %s <filepath>" % sys.argv[0])
        return -1

    if not os.path.isdir(sys.argv[1]):
        print("The specified directory is invalid.")
        print("Usage: %s <filepath>" % sys.argv[0])
        sys.exit(-1)

    basedir = sys.argv[1]

    datadir = os.path.join(basedir, "ops")
    files = sorted(os.listdir(datadir))
    docs = []
    for fn in files:
        basename, ext = os.path.splitext(fn)
        fullname = os.path.join(datadir, fn)
        with open(fullname, "r") as f:
            data = json.loads(f.read())
            docs.append({
                "id": basename,
                "title": basename,
                "body": str(data)
            })
    idx = lunr(ref="id", fields=("title", "body"), documents=docs)
    res = idx.search("update Deployment")
    data = [{'ref': k['ref'], 'score': k['score']} for k in res]
    print(json.dumps(data, indent=2))
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
