#!/usr/bin/env python3

import json
import logging
import sys

from kab.core import jsondiff

logging.basicConfig(level=logging.INFO, format='%(message)s')
LOG = logging.getLogger(__name__)


# MAIN
if __name__ == '__main__':
    if len(sys.argv) != 5:
        LOG.info("Usage: jsondiff <apis> <groups> <versions> <kinds>")
        LOG.info("")
        LOG.info("Each parameter can be specified with two values separated ")
        LOG.info("by a slash. E.g. '1.13/1.14', 'v1/v1beta1'")
        sys.exit(-1)

    result = jsondiff.compare_defs(sys.argv[1].split("/"),
                                   sys.argv[2].split("/"),
                                   sys.argv[3].split("/"),
                                   sys.argv[4].split("/"))
    if result is None:
        LOG.error("Error reading or parsing input file")
        sys.exit(-1)

    if len(result) == 0:
        LOG.info('No difference has been found')
        sys.exit(0)

    LOG.info(json.dumps(result, indent=2))
