#!/usr/bin/env python3

# This script updates all apiVersion and kind descriptions for a specific
# version.

import copy
import json
import jsonref
import os
import shutil
import sys

basedir = "."


def process_definitions(data):
    """Gather definitions.
    """
    global basedir

    defdir = os.path.join(basedir, "defs")
    files = sorted(os.listdir(defdir))
    for fn in files:
        basename, ext = os.path.splitext(fn)
        fullname = os.path.join(defdir, fn)
        data = None
        with open(fullname, "r") as f:
            data = json.loads(f.read())

        if not data:
            continue

        if isinstance(data, dict) and "properties" in data:
            if "apiVersion" in data["properties"]:
                desc = ("The version of the schema for the object "
                        "representation") 
                data["properties"]["apiVersion"]["description"] = desc
            if "kind" in data["properties"]:
                desc = "A string value representing the REST resource"
                data["properties"]["kind"]["description"] = desc

        with open(fullname, "w") as f:
            f.write(json.dumps(data, indent=2, sort_keys=True))

    return


def main():
    global basedir

    if len(sys.argv) < 2:
        print("Usage: change-desc <dir>")
        sys.exit(-1)

    if not os.path.isdir(sys.argv[1]):
        print("The specified directory is invalid.")
        print("Usage: change-desc <dir>")
        sys.exit(-1)

    basedir = sys.argv[1]

    data = {} 
    process_definitions(data)
    sys.exit(0)


if __name__ == "__main__":
    main()
